version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - ./create-script.sql:/docker-entrypoint-initdb.d/create-script.sql
    environment:
      POSTGRES_USER: "uiers"
      POSTGRES_PASSWORD: "hudhsahuDSADas243"
    ports:
      - "5432:5432"